kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: my-go
          image: go-image:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: my-go-svc
spec:
ports:
  - name: http-1080
    port: 1080
    protocol: TCP
    targetPort: 1080
selector:
  app: go-app
